FROM ubuntu:focal

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y software-properties-common systemd python3-pip && rm -rf /var/lib/apt/lists/* \
    && pip3 install ansible git -y

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
